### 代理请求
POST http://localhost:3000/api/fetch

{
    "url": "http://192.168.0.253:9200",
    "method": "POST",
    "headers": {
        "token": "123456"
    },
    "timeout": 5000,
    "data": {},
    "auth": {
        "username": "admin",
        "password": "123456"
    }
}


### 获取全部数据
GET http://localhost:3000/api/db/allDocs?key=""
Content-Type: application/json

### 获取一个数据
POST http://localhost:3000/api/db/get
Content-Type: application/json

{
    "_id": ""
}


### 保存数据
PUT http://localhost:3000/api/db/put
Content-Type: application/json

{
    "_id": "",
    "value": ""
}


### 删除一个数据
DELETE http://localhost:3000/api/db/remove
Content-Type: application/json

{
    "_id": ""
}


