// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    Apache2_0: typeof import('./src/components/License/Apache2_0.vue')['default']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    Bsd: typeof import('./src/components/License/Bsd.vue')['default']
    IndexMapping: typeof import('./src/components/IndexMapping/index.vue')['default']
    JsonDialog: typeof import('./src/components/JsonDialog.vue')['default']
    JsonView: typeof import('./src/components/JsonView/index.vue')['default']
    Mit: typeof import('./src/components/License/Mit.vue')['default']
    TableViewer: typeof import('./src/components/TableViewer/index.vue')['default']
    TabMenu: typeof import('./src/components/TabMenu/index.vue')['default']
    UpdateItem: typeof import('./src/components/UpdateItem/index.vue')['default']
  }
}
