// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('@arco-design/web-vue')['AutoComplete']
    ABacktop: typeof import('@arco-design/web-vue')['Backtop']
    ABackTop: typeof import('@arco-design/web-vue')['BackTop']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    ADescriptionsItem: typeof import('@arco-design/web-vue')['DescriptionsItem']
    ADialog: typeof import('@arco-design/web-vue')['Dialog']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AIcon: typeof import('@arco-design/web-vue')['Icon']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    Apache2_0: typeof import('./src/components/License/Apache2_0.vue')['default']
    APagination: typeof import('@arco-design/web-vue')['Pagination']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    AResult: typeof import('@arco-design/web-vue')['Result']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATimeline: typeof import('@arco-design/web-vue')['Timeline']
    ATimelineItem: typeof import('@arco-design/web-vue')['TimelineItem']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Bsd: typeof import('./src/components/License/Bsd.vue')['default']
    DataView: typeof import('./src/components/DataView/index.vue')['default']
    JsonDialog: typeof import('./src/components/JsonDialog.vue')['default']
    JsonView: typeof import('./src/components/JsonView/index.vue')['default']
    Mit: typeof import('./src/components/License/Mit.vue')['default']
    TableViewer: typeof import('./src/components/TableViewer/index.vue')['default']
    TabMenu: typeof import('./src/components/TabMenu/index.vue')['default']
    UpdateItem: typeof import('./src/components/UpdateItem/index.vue')['default']
  }
}
