enum EventTypeEnum {

    FETCH_REQUEST = '__ES_CLIENT_FETCH_REQUEST__',

    FETCH_RESPONSE = '__ES_CLIENT_FETCH_RESPONSE__',

    LODIS_REQUEST = '__ES_CLIENT_LODIS_REQUEST__',

    LODIS_RESPONSE = '__ES_CLIENT_LODIS_RESPONSE__',

    PING = '__ES_CLIENT_PING__'
}

export default EventTypeEnum;